name: authme-mongodb

services:
  mongodb:
    image: mongo:8.0.10-noble
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    container_name: authme-mongodb
    ports:
      - "4005:27017"
    healthcheck:
      test: |
        echo "
        try { 
          rs.status() 
        } catch (err) { 
          rs.initiate({
            _id: 'rs0',
            members: [
              { _id: 0, host: 'mongodb:27017' }
            ]
          }) 
        }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30